### ISSUE TITLE
Errors following README.md on Mac OS

### ISSUE THREAD

**Issue by Thyroidr** [DillonZChen/goose#7]
Hey Dillon,

When following the README, I encountered some minor issues, just wanted to make sure you are aware.

1. The Mac OS file system (APFS) is file-insensitive. This causes git to complain that it has to discard one of `find_soplex.cmake` and `find_SoPlex.cmake` in `planners/downward_cpu/src/cmake_modules`.
2. It seems that `train_gnn.py` no longer takes a `--seed` argument, but `train.py` still tries to provide it, causing an error.
3. When building with `gcc-11.4.0` (the only gcc11 version available via homebrew on mac), one needs to add the line `#include<set>` to `planners/powerlifted/src/search/datalog/transformations/normal_form.h`.

Everything else seems to work fine for mac.

**Comment by DillonZChen** [comment]
Thanks Ryan,

I've tried to fix the issues by
1. removing the `find_Soplex.cmake` file
2. adding the parameter and actually using the seed
3. adding the line
